# Generated by Django 5.1.3 on 2024-12-24 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='photos',
            field=models.ManyToManyField(related_name='events', to='event.eventphoto'),
        ),
        migrations.AlterField(
            model_name='eventphoto',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_photos', to='event.event'),
        ),
        migrations.AlterField(
            model_name='eventphoto',
            name='image',
            field=models.ImageField(upload_to='event_photos/'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prestataires', models.ManyToManyField(blank=True, related_name='carts', to='event.prestataire')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
