# Generated by Django 5.1.3 on 2025-01-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_checklistitem_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistitem',
            name='event',
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='event_date',
            field=models.DateField(default='2025-01-01'),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='event_name',
            field=models.CharField(default='Unknown Event', max_length=255),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='tasks',
            field=models.JSONField(default=list),
        ),
    ]
