# Generated by Django 5.1.3 on 2025-01-01 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_remove_checklistitem_event_checklistitem_event_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistitem',
            name='tasks',
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='description',
            field=models.TextField(max_length=255),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('is_completed', models.BooleanField(default=False)),
                ('checklist_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='event.checklistitem')),
            ],
        ),
    ]
