# Generated by Django 5.1.3 on 2025-01-01 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_remove_checklistitem_tasks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='checklist_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='event.checklistitem'),
        ),
    ]
