# Generated by Django 5.1.3 on 2025-01-01 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_alter_task_checklist_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevisRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('is_accepted', models.BooleanField(default=None, null=True)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('price_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prestataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devis_responses', to='event.prestataire')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devis_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
