# Generated by Django 5.1.3 on 2025-01-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devisrequest',
            name='is_accepted',
        ),
        migrations.AddField(
            model_name='devisrequest',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devisrequest',
            name='event_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='devisrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('refused', 'Refused')], default='pending', max_length=50),
        ),
    ]
