# Generated by Django 5.1.3 on 2025-01-06 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_alter_payment_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='review',
            new_name='feedback',
        ),
        migrations.RemoveField(
            model_name='eventreservation',
            name='event',
        ),
        migrations.AlterField(
            model_name='availability',
            name='prestataire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='event.prestataire'),
        ),
    ]
